title: Nolboo's Blog

# Oveerriden by GitHub Pages: https://help.github.com/articles/using-jekyll-with-pages#configuring-jekyll
safe: true
highlighter: rouge
lsi: false
future: true

# permalink: pretty   # /blog/:year/:month/:day/:title/
path: "_posts/blog"

# exclude: [vendor]

markdown: kramdown
kramdown:
  input: GFM

gems: 
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-gist

paginate: 10
paginate_path: "/blog/page:num/"

author:
  twitter: n0lb00
  github: nolboo