title: Nolboo's Blog

# Oveerriden by GitHub Pages: https://help.github.com/articles/using-jekyll-with-pages#configuring-jekyll
safe: true
highlighter: rouge
lsi: false
future: true

url: http://nolboo.kim

permalink: pretty   # /blog/:year/:month/:day/:title/
# path: "_posts/blog"

exclude: [vendor]

markdown: kramdown
kramdown:
  input: GFM

gems: 
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-gist

paginate: 10
paginate_path: "/blog/page:num/"

author:
  twitter: n0lb00
  github: nolboo

# staticman:
#   allowedFields: ['name', 'email', 'comment']
#   branch: 'master'
#   filename: ask{@timestamp}
#   format: 'yaml'
#   moderation: true
#   path: _data/ask/{options.post-slug}
#   requiredFields: ['name', 'comment']
#   transforms:
#     email: 'md5'
