title: Nolboo's Blog

# Oveerriden by GitHub Pages: https://help.github.com/articles/using-jekyll-with-pages#configuring-jekyll
safe: false
highlighter: rouge
lsi: false
# future: true

permalink: pretty
# /blog/:year/:month/:day/:title/

exclude: [vendor]

# markdown: kramdown
# kramdown:
#   input: GFM
#   syntax_highlighter: rouge

markdown:     redcarpet

redcarpet:
    extensions: 
      - no_intra_emphasis
      - fenced_code_blocks
      - tables
      - strikethrough
      - superscript
      - autolink
      - hard_wrap

gems: 
      - jekyll-paginate
      - jekyll-gist
      - redcarpet

paginate: 10
paginate_path: /pages/:num

author:
    twitter: n0lb00
    github: nolboo