title: Nolboo's Blog

# Oveerriden by GitHub Pages: https://help.github.com/articles/using-jekyll-with-pages#configuring-jekyll
safe: true
highlighter: rouge
lsi: false
future: true

permalink: pretty   # /blog/:year/:month/:day/:title/
path: "_posts/blog"

exclude: [vendor]

markdown: kramdown
kramdown:
  input: GFM
  # syntax_highlighter: rouge

# markdown:     redcarpet

# redcarpet:
#   extensions: ["no_intra_emphasis", "tables", "autolink", "fenced_code_blocks", "strikethrough"]

gems: 
  - jekyll-paginate
  - jekyll-gist
  - redcarpet

paginate: 10
paginate_path: /pages/:num

author:
  twitter: n0lb00
  github: nolboo